# Generated by Django 3.2.6 on 2021-09-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210831_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='bids',
        ),
    ]
