# Generated by Django 3.2.6 on 2021-09-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctions_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
