# Generated by Django 3.2.6 on 2021-09-01 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='auctions.user'),
            preserve_default=False,
        ),
    ]
