# Generated by Django 3.2.6 on 2021-09-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210901_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
